M48
; DRILL file {KiCad 7.0.1} date Fri 21 Apr 2023 09:19:18 AM PDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-21T09:19:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X93.56Y-114.435
X93.56Y-119.285
T2
X90.53Y-114.135
X90.53Y-119.585
T3
X92.0Y-54.0
X92.0Y-134.0
X206.0Y-54.0
X206.0Y-134.0
T0
M30
